version: '3'
services:

  roaster-monitor-api:
    container_name: roaster-monitor-api
    build: .
    # depends_on:
    #   - db
    environment:
      - PGHOST=${POSTGRES_HOST}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PW}
      - PGDATABASE=${POSTGRES_DB}
      - TZ=America/Toronto
    volumes:
      - '.env:/usr/src/app/.env'
    ports:
      - 3000:${PORT}
    # command: sh -c "/usr/src/app/init.sh && npm start" #run init script and start server
    command: sh -c "npm start" #start server

  # db:
  #   container_name: postgres
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PW}
  #     - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
  #     - TZ=America/Toronto
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: always

# volumes:
#   db-data:
#     driver: local